// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FilePrompt() {
  return window['go']['main']['App']['FilePrompt']();
}

export function ListDatabases() {
  return window['go']['main']['App']['ListDatabases']();
}
