// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadDB(arg1) {
  return window['go']['main']['App']['LoadDB'](arg1);
}

export function MyTest(arg1) {
  return window['go']['main']['App']['MyTest'](arg1);
}
