// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetProjects():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function LoadDB(arg1:string):Promise<void>;

export function MyTest(arg1:string):Promise<string>;
