// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FilePrompt():Promise<boolean>;

export function ListDatabases():Promise<Array<string>>;
